server:
  port: 9050
  servlet:
    context-path: /account

spring:
  datasource:
    url: jdbc:postgresql://localhost:9010/lovable-account-db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

stripe:
  api:
    key: ${STRIPE_API_KEY:}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET:}